version: "3.7"

services:
  db:
    image: mysql:8.0
    container_name: blog_db
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
    ports:
      - 3306:3306

volumes:
  dbvol:
