spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    user: root
    password: password
    locations: classpath:db/migration
